server:
  port: 8480
  read_timeout: 0
  write_timeout: 0
  mode: release
  host: localhost
#  out_url: http://192.168.1.1:8480 # set public service url , port and scheme, you need set this when use nginx and not use default port
upload:
  max_size: 3000MB
  #  upload_dir: uploads
  expire_time: 3600
